Route generator
arbolista-dev/spike-docs pull request #1
Opened 2016-09-27 19:07 UTC by DKbyo

Generates a new route then is added in routes.js, also when new layout is created.

In the same way

npm run generate -- --what route --name route_name

2016-09-29 16:06 UTC, erichulburd requested changes
Tambien me gustaria configurar la manera en que se configuran rutas.

En vez de tener clases, en routes.js, se pueden configurar con las siguientes atributos:
- name: route name
- path
- url: Function que acepta accion y regresa un url traducido.
- parameters: objecto para parsear un url a un objeto.

Ve https://gist.github.com/Arbolista/6c0c766fbec7828fae18a5aaf49958b2 como un ejemplo.

Ademas me gustaria usar esto en vez de https://www.npmjs.com/package/path-to-regexp, para que los urls son mas leibles. Seria lo mejor si podemos aceptar un String o RegExp.

2016-09-29 16:06 UTC, erichulburd commented on gulpfile.babel.js
> +}
Me gustaria mover todo esto a su propio modulo. Por ejemplo, podemos tener modulos:
- route.generator.js
- component.generator.js

en `build-tools/generators`, y gulpfile.babel.js puede llamar estos archivos.

2016-09-29 16:17 UTC, Arbolista commented
Quiero decir: 

Ademas me gustaria usar esto https://www.npmjs.com/package/path-to-regexp para que los urls son mas leibles. Seria lo mejor si podemos aceptar un String o RegExp.

2016-09-29 23:38 UTC, Arbolista commented
Y aqui es un gist de la unica clase de Route que vamos necesitar: https://gist.github.com/Arbolista/dd136d5ea7ea5cfe4c6dd7faa08ef3d8

2016-09-30 22:57 UTC, DKbyo commented
I pushed the path-to-regexp change and created the component.generator.js as you requested, also I delete the routes directories because we don't need them any more.

2016-11-09 20:05 UTC, closed without merging